steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/ecom/ecom-storefront:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://ecom-api-gateway-496160804659.us-east1.run.app/api'
      - '--build-arg'
      - 'CATALOG_SERVICE_URL=https://ecom-catalog-service-496160804659.us-east1.run.app'
      - '.'
    dir: 'storefront'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/ecom/ecom-storefront:latest']
images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/ecom/ecom-storefront:latest'
